"""changed deletion dependancies

Revision ID: 346de1530d84
Revises: b3bc68071fc3
Create Date: 2020-12-18 11:14:24.887909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346de1530d84'
down_revision = 'b3bc68071fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_order', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment_order', 'hirer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_order', 'hirer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment_order', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
