"""equipment orders model added

Revision ID: 48ab8d684fea
Revises: 6af4fe982bf6
Create Date: 2020-12-15 19:07:49.057585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ab8d684fea'
down_revision = '6af4fe982bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_order',
    sa.Column('equipmentorderid', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('hirer_id', sa.Integer(), nullable=False),
    sa.Column('order_begin_date', sa.DateTime(), nullable=False),
    sa.Column('order_return_date_estimate', sa.DateTime(), nullable=True),
    sa.Column('order_actual_return_date', sa.DateTime(), nullable=True),
    sa.Column('order_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['hirer_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('equipmentorderid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_order')
    # ### end Alembic commands ###
